apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: snappy
  labels:
    app: snappy
    component: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: snappy
    component: backend
  type: ClusterIP